name: katex_flutter
description: Performantly render scientific equations using the KaTeX library on Android, iOS and the web platform.
version: 2.3.0+14
homepage: https://gitlab.com/testapp-system/katex_flutter
respsitory: https://gitlab.com/testapp-system/katex_flutter.git
issue_tracker: https://gitlab.com/testapp-system/katex_flutter/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: '^0.3.19+5'
  js: '^0.6.1+1'

dev_dependencies:
  flutter_test:
    sdk: flutter
