name: katex_flutter
description: Performantly render scientific equations using the KaTeX library.
version: 1.0.1+3
homepage: https://gitlab.com/testapp-system-katex_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: '^0.3.19+5'
  js: any

dev_dependencies:
  flutter_test:
    sdk: flutter
